-- liquibase formatted sql

-- changeset aaaa:1721978530922-1
CREATE TABLE "order"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    updated_at    TIMESTAMP(6) WITHOUT TIME ZONE,
    address_id    VARCHAR(255),
    email_address VARCHAR(255)                            NOT NULL,
    phone_number  INTEGER,
    test          VARCHAR(255),
    user_id       VARCHAR(255),
    CONSTRAINT "orderPK" PRIMARY KEY (id)
);

