-- liquibase formatted sql

-- changeset aaaa:1722315361862-1
CREATE TABLE "order" (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE, created_by VARCHAR(255), updated_at TIMESTAMP(6) WITHOUT TIME ZONE, updated_by VARCHAR(255), delivery_fee numeric(38, 2), delivery_method VARCHAR(255), order_status VARCHAR(255), payment_status VARCHAR(255), total_price numeric(38, 2), user_id VARCHAR(255), shipping_address_id BIGINT, CONSTRAINT "orderPK" PRIMARY KEY (id));

-- changeset aaaa:1722315361862-2
CREATE TABLE order_detail (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE, created_by VARCHAR(255), updated_at TIMESTAMP(6) WITHOUT TIME ZONE, updated_by VARCHAR(255), food_id BIGINT, food_name VARCHAR(255), price numeric(38, 2), quantity INTEGER, restaurant_id BIGINT, order_id BIGINT, CONSTRAINT "order_detailPK" PRIMARY KEY (id));

-- changeset aaaa:1722315361862-3
CREATE TABLE shipping_address (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE, created_by VARCHAR(255), updated_at TIMESTAMP(6) WITHOUT TIME ZONE, updated_by VARCHAR(255), address_line1 VARCHAR(255), address_line2 VARCHAR(255), city VARCHAR(255), contact_name VARCHAR(255), country_id BIGINT, country_name VARCHAR(255), district_id BIGINT, district_name VARCHAR(255), phone VARCHAR(255), state_or_province_id BIGINT, state_or_province_name VARCHAR(255), CONSTRAINT "shipping_addressPK" PRIMARY KEY (id));

-- changeset aaaa:1722315361862-4
ALTER TABLE "order" ADD CONSTRAINT UC_ORDERSHIPPING_ADDRESS_ID_COL UNIQUE (shipping_address_id);

-- changeset aaaa:1722315361862-5
ALTER TABLE "order" ADD CONSTRAINT "FKob4wijlmbx7yqe0bjymxcvee0" FOREIGN KEY (shipping_address_id) REFERENCES shipping_address (id);

-- changeset aaaa:1722315361862-6
ALTER TABLE order_detail ADD CONSTRAINT "FKplam7wxc4tjbgex0xyk8f0qxo" FOREIGN KEY (order_id) REFERENCES "order" (id);

