-- liquibase formatted sql

-- changeset hadan:1722153870379-1
CREATE SEQUENCE IF NOT EXISTS "shipping_address_SEQ" START WITH 1 INCREMENT BY 50;

-- changeset hadan:1722153870379-2
CREATE TABLE "order"
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    updated_at          TIMESTAMP(6) WITHOUT TIME ZONE,
    address_id          VARCHAR(255),
    email_address       VARCHAR(255)                            NOT NULL,
    order_status        VARCHAR(255),
    phone_number        INTEGER,
    test                VARCHAR(255),
    user_id             VARCHAR(255),
    shipping_address_id BIGINT,
    CONSTRAINT "orderPK" PRIMARY KEY (id)
);

-- changeset hadan:1722153870379-3
CREATE TABLE shipping_address
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP(6) WITHOUT TIME ZONE,
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255),
    updated_at             TIMESTAMP(6) WITHOUT TIME ZONE,
    address_line1          VARCHAR(255),
    address_line2          VARCHAR(255),
    city                   VARCHAR(255),
    contact_name           VARCHAR(255),
    country_id             VARCHAR(255),
    country_name           VARCHAR(255),
    district_id            VARCHAR(255),
    district_name          VARCHAR(255),
    phone                  VARCHAR(255),
    state_or_province_id   VARCHAR(255),
    state_or_province_name VARCHAR(255),
    CONSTRAINT "shipping_addressPK" PRIMARY KEY (id)
);

-- changeset hadan:1722153870379-4
ALTER TABLE "order"
    ADD CONSTRAINT UC_ORDERSHIPPING_ADDRESS_ID_COL UNIQUE (shipping_address_id);

-- changeset hadan:1722153870379-5
ALTER TABLE "order"
    ADD CONSTRAINT "FKob4wijlmbx7yqe0bjymxcvee0" FOREIGN KEY (shipping_address_id) REFERENCES shipping_address (id);

